### ISSUE TITLE
inconsitent python

### ISSUE THREAD

**Issue by zaro0508** [Sage-Bionetworks-IT/packer-base-amazonlinux2#3]
currently pip is set to pip3 but python is still python2?  need to set both to python 3 or neither.  this may help.. https://sixbyseven.dev/how-to-install-python-3-x-on-amazon-ec2-instance/

**Comment by thomasyu888** [comment]
We can't use python3 as the default on amazonlinux 2 because we won't be able to ssh into it. I will remove change pip3 as default.
